### PR TITLE
docs: update import module getting start

### PR DESCRIPTION
**Pull request by alanmatiasdev**
This hotfix only adjusts the README on how to import the project.

### CODE REVIEW

**Comment by manoelcfeliciano** [comment]
Why are you having to import like that?

For me, the code below works just fine.

```
import moipSdk from 'moip-sdk-node-ts';

moipSdk.connect({
	production: false,
	accessToken: 'secret',
});
```

**Comment by alanmatiasdev** [comment]
> Why are you having to import like that?
> 
> For me, the code below works just fine.
> 
> ```
> import moipSdk from 'moip-sdk-node-ts';
> 
> moipSdk.connect({
> 	production: false,
> 	accessToken: 'secret',
> });
> ```

I'm not sure. When using the lib in my provider, I can't instantiate it in the exact way it appears in the documentation, only in the proposed format. I haven't tested it on other projects yet.

Captura de Tela 2022-03-18 às 09 27 16

**Comment by manoelcfeliciano** [comment]
> > Why are you having to import like that?
> > For me, the code below works just fine.
> > ```
> > import moipSdk from 'moip-sdk-node-ts';
> > 
> > moipSdk.connect({
> > 	production: false,
> > 	accessToken: 'secret',
> > });
> > ```
> 
> I'm not sure. When using the lib in my provider, I can't instantiate it in the exact way it appears in the documentation, only in the proposed format. I haven't tested it on other projects yet.
> 
> Captura de Tela 2022-03-18 às 09 27 16

I must say this behavior is a little awkward. I made a minimal example at CodeSandbox and it seems to work fine.

https://codesandbox.io/s/holy-snow-gkdemq?file=/src/index.ts

**Comment by alanmatiasdev** [comment]
> > > Why are you having to import like that?
> > > For me, the code below works just fine.
> > > ```
> > > import moipSdk from 'moip-sdk-node-ts';
> > > 
> > > moipSdk.connect({
> > > 	production: false,
> > > 	accessToken: 'secret',
> > > });
> > > ```
> > 
> > 
> > I'm not sure. When using the lib in my provider, I can't instantiate it in the exact way it appears in the documentation, only in the proposed format. I haven't tested it on other projects yet.
> > Captura de Tela 2022-03-18 às 09 27 16
> 
> I must say this behavior is a little awkward. I made a minimal example at CodeSandbox and it seems to work fine.
> 
> https://codesandbox.io/s/holy-snow-gkdemq?file=/src/index.ts

Strange. It could be some configuration of my project.

Captura de Tela 2022-03-18 às 10 18 06

`
import moipSdk
This expression is not callable.
  Type 'typeof import("PROJECT_PATH/node_modules/moip-sdk-node-ts/dist/lib/index")' has no call signatures.ts(2349)
`

This is resolved when performing the instance with the default (according to PR) or when I change the import of index.ts to the following:

code

**Comment by manoelcfeliciano** [comment]
> > > > Why are you having to import like that?
> > > > For me, the code below works just fine.
> > > > ```
> > > > import moipSdk from 'moip-sdk-node-ts';
> > > > 
> > > > moipSdk.connect({
> > > > 	production: false,
> > > > 	accessToken: 'secret',
> > > > });
> > > > ```
> > > 
> > > 
> > > I'm not sure. When using the lib in my provider, I can't instantiate it in the exact way it appears in the documentation, only in the proposed format. I haven't tested it on other projects yet.
> > > Captura de Tela 2022-03-18 às 09 27 16
> > 
> > 
> > I must say this behavior is a little awkward. I made a minimal example at CodeSandbox and it seems to work fine.
> > https://codesandbox.io/s/holy-snow-gkdemq?file=/src/index.ts
> 
> Strange. It could be some configuration of my project.
> 
> Captura de Tela 2022-03-18 às 10 18 06
> 
> `import moipSdk This expression is not callable. Type 'typeof import("PROJECT_PATH/node_modules/moip-sdk-node-ts/dist/lib/index")' has no call signatures.ts(2349)`
> 
> This is resolved when performing the instance with the default (according to PR) or when I change the import of index.ts to the following:
> 
> code

Ah, right. The documentation is indeed wrong. You should do the following:

```
this.client = moipSdk.connect({ ... })
```

**Comment by alanmatiasdev** [comment]
> > > > > Why are you having to import like that?
> > > > > For me, the code below works just fine.
> > > > > ```
> > > > > import moipSdk from 'moip-sdk-node-ts';
> > > > > 
> > > > > moipSdk.connect({
> > > > > 	production: false,
> > > > > 	accessToken: 'secret',
> > > > > });
> > > > > ```
> > > > 
> > > > 
> > > > I'm not sure. When using the lib in my provider, I can't instantiate it in the exact way it appears in the documentation, only in the proposed format. I haven't tested it on other projects yet.
> > > > Captura de Tela 2022-03-18 às 09 27 16
> > > 
> > > 
> > > I must say this behavior is a little awkward. I made a minimal example at CodeSandbox and it seems to work fine.
> > > https://codesandbox.io/s/holy-snow-gkdemq?file=/src/index.ts
> > 
> > 
> > Strange. It could be some configuration of my project.
> > Captura de Tela 2022-03-18 às 10 18 06
> > `import moipSdk This expression is not callable. Type 'typeof import("PROJECT_PATH/node_modules/moip-sdk-node-ts/dist/lib/index")' has no call signatures.ts(2349)`
> > This is resolved when performing the instance with the default (according to PR) or when I change the import of index.ts to the following:
> > code
> 
> Ah, right. The documentation is indeed wrong. You should do the following:
> 
> ```
> this.client = moipSdk.connect({ ... })
> ```

That solves it :smiley:

**Pull request closed without merging**
