### PR TITLE
feat: add access token param to get balance request

### PR DESCRIPTION
**Pull request by alanmatiasdev**
This feature allows the user to pass an access token to access the Moip balance. This method makes it possible to search the balance of transparent accounts from a PRIMARY.

### CODE REVIEW

**Comment by manoelcfeliciano** [comment]
Why you cannot pass this `OAuth access_token` under the opts parameter in getOne function?

For example:

```
getOne({ auth: 'OAuth access_token'  })
```

or setting this globally by creating a new instance from connect:

```
import moipSdk from 'moip-sdk-node-ts';

moipSdk.connect({
    production: false,
    accessToken: ''
});
```

**Comment by alanmatiasdev** [comment]
> Why you cannot pass this `OAuth access_token` under the opts parameter in getOne function?
> 
> For example:
> 
> ```
> getOne({ auth: 'OAuth access_token'  })
> ```
> 
> or setting this globally by creating a new instance from connect:
> 
> ```
> import moipSdk from 'moip-sdk-node-ts';
> 
> moipSdk.connect({
>     production: false,
>     accessToken: ''
> });
> ```

The opts parameter inside the balance getOne function is omitted. In this case, in order not to change this, I thought of another solution. I even thought about opening an issue to check the best way to do this. 

What do you believe is the best way?

**Comment by manoelcfeliciano** [comment]
> > Why you cannot pass this `OAuth access_token` under the opts parameter in getOne function?
> > For example:
> > ```
> > getOne({ auth: 'OAuth access_token'  })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or setting this globally by creating a new instance from connect:
> > ```
> > import moipSdk from 'moip-sdk-node-ts';
> > 
> > moipSdk.connect({
> >     production: false,
> >     accessToken: ''
> > });
> > ```
> 
> The opts parameter inside the balance getOne function is omitted. In this case, in order not to change this, I thought of another solution. I even thought about opening an issue to check the best way to do this.
> 
> What do you believe is the best way?

You are right about that externally, but you could still do something like the following:

```
const getOne = (opts: HttpOpts, accessToken?: string) => api.get({ ...opts, auth: `OAuth ${accessToken}` }, '/balances');
```

What do you think about this approach?

This way you don't need to create a new api variation file just for that.

**Comment by alanmatiasdev** [comment]
> > > Why you cannot pass this `OAuth access_token` under the opts parameter in getOne function?
> > > For example:
> > > ```
> > > getOne({ auth: 'OAuth access_token'  })
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > or setting this globally by creating a new instance from connect:
> > > ```
> > > import moipSdk from 'moip-sdk-node-ts';
> > > 
> > > moipSdk.connect({
> > >     production: false,
> > >     accessToken: ''
> > > });
> > > ```
> > 
> > 
> > The opts parameter inside the balance getOne function is omitted. In this case, in order not to change this, I thought of another solution. I even thought about opening an issue to check the best way to do this.
> > What do you believe is the best way?
> 
> You are right about that externally, but you could still do something like the following:
> 
> ```
> const getOne = (opts: HttpOpts, accessToken?: string) => api.get({ ...opts, auth: `OAuth ${accessToken}` }, '/balances');
> ```
> 
> What do you think about this approach?
> 
> This way you don't need to create a new api variation file just for that.

That was exactly the first solution I had thought of. I will update the code.

**Comment by manoelcfeliciano** [comment]
Thanks for the changes! I will merge it. :)

**Pull request merged**
